### ISSUE TITLE
单台服务器删除逻辑似乎还有点问题

### ISSUE THREAD

**Issue by f118** [hequan2017/autoops#4]
有时候点了没有反应，有时候点了之后点取消无法取消。

**Comment by hequan2017** [comment]
好的 我回头再测试一下 原来测试的时候 时有时没有




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            
                            
                            
                                
                                    邮箱：hequan2011@sina.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
在2018年01月09日 18:46，f118 写道： 有时候点了没有反应，有时候点了之后点取消无法取消。

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/hequan2017/autoops","title":"hequan2017/autoops","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/hequan2017/autoops"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"单台服务器删除逻辑似乎还有点问题 (#4)"}],"action":{"name":"View Issue","url":"https://github.com/hequan2017/autoops/issues/4"}}}

**Comment by hequan2017** [comment]
BUG 已修复，原因为 swal  的代码搞错了。

**Comment by f118** [comment]
我fork了一版，是那个原因吗




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            杨剑
                            
                            
                                
                                    邮箱：f118@sina.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
在2018年01月11日 10:07，何全 写道： BUG 已修复，原因为 swal  的代码搞错了。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/hequan2017/autoops","title":"hequan2017/autoops","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/hequan2017/autoops"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hequan2017 in #4: BUG 已修复，原因为 swal  的代码搞错了。"}],"action":{"name":"View Issue","url":"https://github.com/hequan2017/autoops/issues/4#issuecomment-356801351"}}}

**Comment by hequan2017** [comment]
是因为   前端代码   js 多了两行 造成了，已修改，请fork 现在 最新版本

**Comment by f118** [comment]
收到




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            杨剑
                            
                            
                                
                                    邮箱：f118@sina.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
在2018年01月11日 10:29，何全 写道： 是因为   前端代码   js 多了两行 造成了，已修改，请fork 现在 最新版本

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/hequan2017/autoops","title":"hequan2017/autoops","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/hequan2017/autoops"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hequan2017 in #4: 是因为   前端代码   js 多了两行 造成了，已修改，请fork 现在 最新版本"}],"action":{"name":"View Issue","url":"https://github.com/hequan2017/autoops/issues/4#issuecomment-356805045"}}}
